### PR TITLE
New Database Schema

### PR DESCRIPTION
**Pull request by pdarg**
Remove old database migrations
Add new database migrations

### CODE REVIEW

**Comment by pdarg** [comment]
Lots of changes, this is going to require some tweaking of the import code and converting the old data to the new format

**Comment by crast** [comment]
Couldn't we have just made new migrations to migrate the data, instead of starting from scratch?

**Comment by pdarg** [comment]
We still can. I did it this way so you could see all of the fields. Does this match what you created?

**Comment by pdarg** [comment]
Opened https://github.com/pdarg/tmlpstats/pull/41

**Pull request closed without merging**
